
title: Jhon Cruz Resume
url: 'https://jacruzca.github.io'
baseurl: '/jacruzca' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Jhon Cruz
tagline: Web and mobile Developer
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: jhon.unal@gmail.com
phone: +57 317 669 8633
website: jacruzca.github.io #do not add http://
linkedin: jacruzca
github: jacruzca
twitter: '@jacruzca'


# Tracker
analytics: UA-83979019-1
#Update all the sections by editing the files inside _includes folder.
